---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(magrittr)
library(ggbeeswarm)
library(ggpubr)
setwd("/DeepenData/Repos/geometric_cobra")

#metabolite_data        <- read_csv("./metabolites_data/metabolite_data.csv")
#subsys_fluxes_non_zero <- arrow::read_parquet("./results/flux/subsys_fluxes_non_zero.parquet.gzip")
metabolite_data        <- arrow::read_parquet("./metabolites_data/metabolites_outliers_imputed.parquet.gzip")



get_vars_by_quntl <- function(df){
                                df %>% 
                                summarise(across(where(is.double),  ~ mean(.x, na.rm = TRUE))) %>% t -> vars_mean
                              q_25 <- quantile(vars_mean, 0.25, na.rm = TRUE)[[1]]
                              q_50 <- quantile(vars_mean, 0.5, na.rm = TRUE)[[1]]
                              q_75 <- quantile(vars_mean, 0.75, na.rm = TRUE)[[1]]
                              
                              vars_q_1 <- vars_mean[vars_mean < q_25,] %>% names 
                              vars_q_2 <- vars_mean[q_25 <= vars_mean & vars_mean < q_50,] %>% names 
                              vars_q_3 <- vars_mean[q_50 <= vars_mean &   vars_mean < q_75,] %>% names 
                              vars_q_4 <- vars_mean[q_75 <= vars_mean ,] %>% names 
                              return(list(vars_q_1, vars_q_2, vars_q_3, vars_q_4))
}

foo <- function(plot){
                                                  p <- ggplot_build(plot)
                             p$data[[1]] <-   p$data[[1]] %>%
                               mutate(diff = abs(x-round(x)), x = case_when(group %% 2 == 0 ~ round(x) + diff,
                                                    TRUE ~ round(x) - diff)) %>%    select(-diff)
                             
                             
                             return(
                               (ggplot_gtable(p))
                             )
                             
                            }
plot_split_violins <- function(data, quntl_num,vars_by_quntl ,legend.position, logscale, alpha, size_marker){
                          colours <- c(alpha(c( "dodgerblue2"), alpha), alpha(c("darkorange"), 1))
                          #data %>% get_vars_by_quntl -> vars_by_quntl
                          
                          
                          
                          p <- data %>%  select(c(vars_by_quntl[[quntl_num]], "Group")) %>%  pivot_longer(-Group)  %>% 
                          ggplot(aes(name,value,color= Group))+ 
                          geom_quasirandom(size= size_marker) + #scale_fill_manual(values = colours, name = "") +
                          theme_minimal()+
                          guides(color = guide_legend(override.aes = list(size = 4, alpha = 1) ))+ 
                          theme(axis.title.x = element_blank(),axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
                                  axis.title.y = element_blank(), legend.position=legend.position,
                                 legend.text = element_text(size=7))+scale_color_discrete(name="")+
                            scale_colour_manual(values = colours, name = "") 
                          
                          if(logscale){p <-p  + coord_trans( y="log2") }
                          
                          return(foo(p) %>% as_ggplot)  }


metabolite_data %>% dplyr::select(-c('Phe')) %>% get_vars_by_quntl -> vars_by_quntl

vars_by_quntl[[5]] <- c('Phe')

a_subplot <-plot_split_violins(metabolite_data, 5 , vars_by_quntl, 'top', TRUE, .1, .6)
b_subplot <- plot_split_violins(metabolite_data, 4 , vars_by_quntl, 'none', F, .02, .01)
c_subplot <- plot_split_violins(metabolite_data, 3 , vars_by_quntl, 'none', F, .02, .01)
d_subplot <- plot_split_violins(metabolite_data, 2 , vars_by_quntl, 'none', F, .02, .01)
e_subplot <- plot_split_violins(metabolite_data, 1 , vars_by_quntl, 'none', F, .02, .01)
```


```{r fig.height=6, fig.width=5, message=FALSE, warning=FALSE}

right_swarms <- ggarrange(b_subplot, c_subplot, d_subplot, e_subplot, ncol = 1, labels = c("b","c","d","e"), vjust = 1.1, hjust = .5)



ggarrange(a_subplot, right_swarms, widths = c(.55, 1), labels = c("a",""), vjust = 1.1) -> swarm_panel


```

```{r}
make_umap <- function(data, legend.position){UMAPM <- umap::umap(data  %>% select_if(is.numeric) %>% 
                                                                        as.matrix(), n_neighbors = 20, scale = T, n_threads = 20, fast_sgd = F, metric = 'cosine', spread = 10)
                       
                                                       

p <- ggplot(as_tibble(UMAPM$layout), aes(V1, V2, colour= data[["Group"]]))
                                                        UMAP_reduction <-  p + geom_point(size= .2) + xlab('UMAP dimension 1') + ylab('UMAP dimension 2')+
                                                          scale_colour_manual(values =  c(alpha(c( "dodgerblue2"), .5), alpha(c("darkorange"), 1)))+ 
                                                          theme(legend.position=legend.position, text = element_text(size = 9), axis.title.y = element_text(size = 7),  axis.title.x = element_text(size = 7))   +
                                                             guides(color = guide_legend(override.aes = list(size = 3) ) )+guides(color = guide_legend(title = "Group", override.aes = list(size = 3) )) 
                                                        return(UMAP_reduction)}

metabolite_data %>% make_umap('none') -> umap_plot_1
```


```{r}
setwd("/DeepenData/Repos/geometric_cobra")

augmented_metabolite_data <- arrow::read_parquet("./results/dataframes/augmented_metabolite_data_v2.parquet.gzip") 


augmented_metabolite_data %>% 
  rename( Group = label) %>% mutate(Group = if_else(Group == 1,'PKU','Control')) %>% make_umap('none')-> umap_plot_2


```


```{r}



setwd("/DeepenData/Repos/geometric_cobra")

img <- png::readPNG("./results/figures/RECON_graph.png")

graph <- ggplot() + background_image(img)



```
```{r}
plot_swarm       <- function(df, size, alpha){
                              df%>% pivot_longer(everything()) -> long
                              ggplot(long,aes(name, value)) + geom_quasirandom(size=size, alpha = alpha, aes(color='red4')) -> my_plot
                              return(my_plot)}







p <- subsys_fluxes_non_zero[,colSums(subsys_fluxes_non_zero)%>%abs > 1] %>% sample_n(1000) %>% abs %>% plot_swarm(.2,.2) 

flux_subplot <- p + ylim(c(0,5.9)) + 
  xlab('Reaction')+ ylab('Flux') + theme_minimal() +  theme(legend.position = 'none', axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

```


```{r fig.height=6, fig.width=7.5}
umap_panel <-  ggarrange(umap_plot_1, umap_plot_2, widths = c(1,1))

ggarrange(umap_panel, graph, flux_subplot, ncol = 1, heights = c(.4,1,.55), labels = c("f","g","h"),  vjust = 1.1, hjust = .5) -> right_panel

ggarrange(swarm_panel, right_panel, ncol = 2, widths = c(1,.7)) -> figure_1_panel

```


```{r fig.height=6, fig.width=7.5}
setwd("/DeepenData/Repos/geometric_cobra")

ggsave("./results/figures/Figure_1.png", 
       figure_1_panel, height=6.5, width=8, bg = "white")

```


#####################################################################################################################################################
######################################################################################################################################################
```{r message=FALSE, warning=FALSE}
get_data_subset <- function(df , condition, aminoacids){
                                        df %<>%  select(!dplyr::matches('SA')) %>%
                                        dplyr::filter(Group==condition) %>% 
                                        select_if(is.numeric) 
                                        if(aminoacids){df %<>% select(!dplyr::matches('C\\d+'))
                                        } else {df %<>% select(dplyr::matches('C\\d+'))}
                                        return(df)}
 
AAs_PKU        <- get_data_subset(metabolite_data, "PKU", T)
AcylCs_PKU     <- get_data_subset(metabolite_data, "PKU", F)
AAs_Control    <- get_data_subset(metabolite_data, "Control", T)
AcylCs_Control <- get_data_subset(metabolite_data, "Control", F)
```

```{r message=FALSE, warning=FALSE}
library(ComplexHeatmap)

plot_densityHeatmap <- function(df, title, pallete){
    return(
   ggplotify::as.ggplot(densityHeatmap(df %>% scale , ylim = c(-1.5, 1.5), cluster_columns = TRUE, title = title, ylab = "", col = pallete,
                                                     title_gp = gpar(fontsize = 6), tick_label_gp = gpar(fontsize = 6), quantile_gp = gpar(fontsize = 6),
                                                     column_names_gp = gpar(fontsize = 6),column_names_rot = 50 )) 
    )}


FLUX_PKU_plot  <- subsys_fluxes_non_zero  %>% plot_densityHeatmap("", rev(RColorBrewer::brewer.pal(11, "RdYlGn")))


```

```{r fig.height=8, fig.width=5, message=FALSE, warning=FALSE}
library(ggpubr)

AAs_Control_plot  <- AAs_Control %>% plot_densityHeatmap("", rev(RColorBrewer::brewer.pal(11, "Spectral")))
AcylCs_Control_plot <- AcylCs_Control %>% plot_densityHeatmap("", rev(RColorBrewer::brewer.pal(11, "Spectral")))
AAs_PKU_plot <- AAs_PKU %>% plot_densityHeatmap("", rev(RColorBrewer::brewer.pal(11, "Spectral")))
AcylCs_PKU_plot <- AcylCs_PKU %>% plot_densityHeatmap("", rev(RColorBrewer::brewer.pal(11, "Spectral")))


densityHeatmap_panel <- ggarrange(AAs_Control_plot, AcylCs_Control_plot,
                                  AAs_PKU_plot, AcylCs_PKU_plot, 
                                  ncol = 1 ,  common.legend = T, heights = c(.75,1,.75,1), labels = c("a","b","c","d"))

```

```{r fig.height=4, fig.width=7, message=FALSE, warning=FALSE}
library(umap)

make_umap <- function(AAs_Control, AcylCs_Control,AAs_PKU, AcylCs_PKU){
                                                          data_control <-cbind(AAs_Control,AcylCs_Control)
                                                        data_PKU     <- cbind(AAs_PKU,AcylCs_PKU)
                                                        data_control["Group"] <- "Control"
                                                        data_PKU["Group"] <- "PKU"
                                                        
                                                        data <- rbind(data_PKU,data_control)
                                                        
                                                        UMAPM <- umap(data  %>% select_if(is.numeric) %>% 
                                                                        as.matrix(), n_neighbors = 50, scale = T, n_threads = 20, fast_sgd = F, metric = 'cosine', spread = 10)
                                                        p <- ggplot(as_tibble(UMAPM$layout), aes(V1, V2, colour= data[["Group"]]))
                                                        UMAP_reduction <-  p + geom_point(size= .2) + xlab('UMAP dimension 1') + ylab('UMAP dimension 2')+
                                                          scale_colour_manual(values = c("cadetblue", "blue"))+ theme(text = element_text(size = 9))   +
                                                             guides(color = guide_legend(override.aes = list(size = 3) ) )+guides(color = guide_legend(title = "Group", override.aes = list(size = 3) )) 
                                                        return(UMAP_reduction)}

umap_original_data<- make_umap(AAs_Control, AcylCs_Control,AAs_PKU, AcylCs_PKU)
umap_original_data
```

```{r}
setwd("/DeepenData/Repos/geometric_cobra")

augmented_metabolite_data <- arrow::read_parquet("./results/dataframes/augmented_metabolite_data_v2.parquet.gzip")
augmented_metabolite_data <- rename(augmented_metabolite_data, Condicion = label) %>% dplyr::mutate(Condicion = if_else(Condicion== 1, 'PKU', 'Control'))


AAs_PKU_2        <- get_data_subset(augmented_metabolite_data, "PKU", T)
AcylCs_PKU_2     <- get_data_subset(augmented_metabolite_data, "PKU", F)
AAs_Control_2    <- get_data_subset(augmented_metabolite_data, "Control", T)
AcylCs_Control_2 <- get_data_subset(augmented_metabolite_data, "Control", F)

umap_augmented_data <- make_umap(AAs_Control_2, AcylCs_Control_2,AAs_PKU_2, AcylCs_PKU_2)
umap_augmented_data
```
```{r fig.height=8, fig.width=10, message=FALSE, warning=FALSE}


umap_panel <- ggarrange(umap_original_data, umap_augmented_data, common.legend = T, labels = c("e","f"), vjust = .5, hjust = .5)

setwd("/DeepenData/Repos/geometric_cobra")

img <- png::readPNG("./results/figures/RECON_graph.png")

graph <- ggplot() + background_image(img)



UMAP_plus_graph <- ggarrange(umap_panel, graph,FLUX_PKU_plot, ncol = 1, heights = c(1, 2.5, 1), labels = c("","g","h"))
ggarrange(densityHeatmap_panel, UMAP_plus_graph, widths = c(.95,1), ncol = 2) -> panel

ggsave("/DeepenData/Repos/geometric_cobra/results/figures/Figure_1.png", 
       panel, height=8, width=9, bg = "white")
```


```{r message=FALSE, warning=FALSE}
setwd("/DeepenData/Repos/geometric_cobra")

augmented_metabolite_data <- arrow::read_parquet("./results/dataframes/augmented_metabolite_data_v2.parquet.gzip") 



augmented_metabolite_data




```




























