---
title: "R Notebook"
output: html_notebook
---
```{r message=FALSE, warning=FALSE}
library(arrow)
library(tidyverse)
library(ComplexHeatmap) 
library(scales)

setwd("/DeepenData/Repos/geometric_cobra")
df <- read_csv("./results/data/results_for_R.csv") %>% select(-c("...1"))
labels <- read_csv("./results/data/results_for_R_labels.csv") %>% select(-c("...1")) %>% .[[1]]
edge_weights_x_patients <- df%>% select_if(is.numeric)
edges_genes   <- df%>% select_if(is.character)
n_edges <- nrow(edges_genes)
n_patients <- length(labels)
```

```{r}
edges_mask    <- sample(c(T,F), n_edges, replace = T, prob = c(.7, .3))
patients_mask <- sample(c(T,F), n_patients, replace = T, prob = c(.15, .85))
edge_weights_x_patients_SAMPLE <- edge_weights_x_patients[edges_mask,patients_mask]
labels_SAMPLE <- labels[patients_mask]
edges_genes_SAMPLE <- edges_genes[edges_mask,]
processed_data <- edge_weights_x_patients_SAMPLE %>% as.matrix() %>% scale %>% rescale
```


```{r}
right_annotation = rowAnnotation(Phenotype = labels_SAMPLE)
ht <- Heatmap(t(processed_data), row_km = 2, column_km = 3,  show_column_names = F, show_row_names = F, right_annotation= right_annotation)
heatmap_clusters <- waRRior::heatmap_extract_cluster(draw(ht), t(processed_data),  which = "column")

```
```{r}
get_entrez_IDs_cluster <- function(a_cluster) {
  
                                                edges_clusters   <-  heatmap_clusters[['Cluster']]
                                                cluster_mask     <- edges_clusters ==a_cluster
                                                
                                                genes_list       <- edges_genes_SAMPLE$genes[cluster_mask] %>% str_extract_all('\\d+(?=\\.)')
                                                entrez_IDs       <- genes_list%>% unlist() %>% unique()
                                                return(entrez_IDs)}


clusters <- unique(heatmap_clusters[['Cluster']])
lapply(clusters, get_entrez_IDs_cluster)

```
























