---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
library(arrow)
library(tidyverse)
library(ComplexHeatmap) 
library(scales)
library(ggpubr)
library(ggplot2)
library(DOSE)
library(magrittr)
library(biomaRt)
library(tidyverse)
library(clusterProfiler)
library(ReactomePA)
library(org.Hs.eg.db)
library(fastcluster)

setwd("/DeepenData/Repos/geometric_cobra")
C_genes  <- read_csv( "./results/explanations/to_GraphTools_visualization_explanatory_subgraph_MASKED_GIN_Concentration.csv")    %>%  .[['genes']]  %>% str_extract_all('\\d+(?=\\.)') %>% unlist() %>% unique()
F_genes  <- read_csv( "./results/explanations/to_GraphTools_visualization_explanatory_subgraph_MASKED_GIN_FLUX.csv")    %>%  .[['genes']]  %>% str_extract_all('\\d+(?=\\.)') %>% unlist() %>% unique()
CF_genes <- read_csv( "./results/explanations/to_GraphTools_visualization_explanatory_subgraph_MASKED_GIN_Concen_plus_Fluxes.csv")    %>%  .[['genes']]  %>% str_extract_all('\\d+(?=\\.)') %>% unlist() %>% unique()
#ensembl    <- useMart("ensembl")
Hs.ensembl <- useMart("ensembl",dataset="hsapiens_gene_ensembl")
```


```{r message=FALSE, warning=FALSE}

genes_symbols <- list()
get_functional_annots <- function(entrez_IDs, transporters = F){
                                   temp <- getBM(attributes=c('hgnc_symbol',"entrezgene_id", 'entrezgene_description'),filters ='entrezgene_id',values =entrez_IDs, mart = Hs.ensembl)
                                   if(transporters){
                                     temp %<>% filter(str_detect(entrezgene_description,regex( '(solute.+?carrier)|transporter|aquapor|transport', ignore_case = T))) 
                                   }
                                   else {  temp %<>% filter(!str_detect(entrezgene_description,regex( '(solute.+?carrier)|transporter|aquapor|transport', ignore_case = T))) }
                                   
                                   
                                   
                                   return(arrange(temp, hgnc_symbol) %>% purrr::set_names(c("Symbol", "Entrez ID", "Description")))}



get_transporters_and_reactions <- function(genes_entrez){
                                            reactions    <- get_functional_annots(genes_entrez, transporters = F) 
                                            transporters <- get_functional_annots(genes_entrez, transporters = T) 
                                            
                                            transporters_and_reactions <- list('reactions'=reactions,'transporters'=transporters)
                                            return(transporters_and_reactions)}

get_two_Entrez_gene_lists <- function(rxns_and_transps_list){
                            return(list(rxns_and_transps_list$reactions$`Entrez ID`, rxns_and_transps_list$transporters$`Entrez ID`) %>% purrr::set_names(c("rxns", "trns"))
)
}

get_transporters_and_reactions(C_genes) ->  Concentration_rxns_and_transps
get_transporters_and_reactions(F_genes) ->  Flux_rxns_and_transps
get_transporters_and_reactions(CF_genes) -> FluxConcentration_rxns_and_transps
```



```{r message=FALSE, warning=FALSE}
setwd("/DeepenData/Repos/geometric_cobra/")
res <- readRDS("./results/genes/RNA_results.RDS")
res %>% rownames() -> all_ENSMUST
#Hs.ensembl       <- useMart("ensembl",dataset="hsapiens_gene_ensembl")
Mm.ensembl       <- useMart("ensembl",dataset="mmusculus_gene_ensembl")
temp_1           <- getBM(attributes=c('ensembl_transcript_id','hsapiens_homolog_ensembl_gene'),filters ='ensembl_transcript_id',values =all_ENSMUST, mart = Mm.ensembl)
colnames(temp_1) <- c("mouse_ensembl_transcript_id", "hsapiens_ensembl")
temp_2           <- getBM(attributes=c('ensembl_gene_id','hgnc_symbol','entrezgene_id','entrezgene_description'), 
                    filters ='ensembl_gene_id',values = temp_1$hsapiens_ensembl, mart = Hs.ensembl)


colnames(temp_2)           <- c("hsapiens_ensembl", "hgnc_symbol", "entrezgene_id", 'description')

inner_join(temp_1, temp_2) -> all_gene_codes
res['mouse_ensembl_transcript_id'] <- rownames(res)


inner_join(as.data.frame(res) ,all_gene_codes ) %>% drop_na() %>% arrange(hgnc_symbol) -> annotated_results
```

```{r}
library(EnhancedVolcano)
library(magrittr)

get_processed_results <- function(annotated_results, subset){
  annotated_results %>% dplyr::filter(entrezgene_id %in% subset) %>% dplyr::select(-c(mouse_ensembl_transcript_id,hsapiens_ensembl,entrezgene_id, description)) %>%
  group_by(hgnc_symbol) %>% summarise_all(median,  na.rm = TRUE) ->processed_results
  return(processed_results)
}




make_volcano <- function(df_res,labSize, subtitle, pValue_cutoff     = 0.05, FoldChnage_cutoff = .1){plot <- EnhancedVolcano(
        df_res, 
        x = 'log2FoldChange',
        y = 'padj',
        title = NULL,
        subtitle = subtitle,#paste0( names( conjuntos )[[i]], " - ", length( unique(conjuntos[[i]][ conjuntos[[i]] %in% df_res$gene_symbol_sig ]) ), " trancripts" ),
        pCutoff = pValue_cutoff,
        FCcutoff = FoldChnage_cutoff,
        pointSize = 3,
        lab = df_res$hgnc_symbol,
        #legendPosition = 'right',
        labSize = labSize,
        boxedLabels = T,
        drawConnectors = TRUE,
        widthConnectors = 0.2,
        colConnectors = 'black',
        max.overlaps = 200, #Inf,
    )+ ggthemes::theme_few() #+ 
    # coord_flip() + 
    #theme(legend.position="bottom")
    return(plot)}
```


```{r fig.height=18, fig.width=18, message=FALSE, warning=FALSE}
make_volcano_panel <- function(rxns_and_transps, labSize_1 =3, labSize_2=3,  widths = c(1,.5), pValue_cutoff = 0.05, common.legend.pos = 'top', left_y_limts = c(0,10), right_y_limts = c(0,10)){
                                  get_processed_results(annotated_results, rxns_and_transps %>% get_two_Entrez_gene_lists %>% .[['rxns']]) -> Flux_rxns
                                  get_processed_results(annotated_results, rxns_and_transps %>% get_two_Entrez_gene_lists %>% .[['trns']]) -> Flux_trns
                                  
                                  volcano_panel <- ggarrange(make_volcano(Flux_rxns, labSize = labSize_1, subtitle = 'Reactions', pValue_cutoff = pValue_cutoff) + ylim(left_y_limts), 
                                                             make_volcano(Flux_trns, labSize = labSize_2, subtitle = 'Transporters', pValue_cutoff=pValue_cutoff) + ylim(right_y_limts), nrow = 1, widths = widths, common.legend = T, legend = common.legend.pos)
                                  return(volcano_panel)}




C_volcano  <- make_volcano_panel(Concentration_rxns_and_transps, 2,2, c(1,1),     pValue_cutoff    = 0.05, left_y_limts = c(0,10), right_y_limts = c(0,10))
F_volcano  <- make_volcano_panel(Flux_rxns_and_transps, 2,2, widths =c(2.7,1),                      pValue_cutoff  = 0.01, common.legend.pos = 'none',left_y_limts = c(0,20.42), right_y_limts = c(0,12.5))
CF_volcano <- make_volcano_panel(FluxConcentration_rxns_and_transps, 2,2, widths =c(2.5,1),pValue_cutoff = 0.01, common.legend.pos = 'none', left_y_limts = c(0,20.42), right_y_limts = c(0,12.5))

volcanos_panel   <- ggarrange(C_volcano, F_volcano, CF_volcano, ncol = 1, common.legend = T, heights = c(.4,1,1), labels = c("b","d","f"))
volcanos_panel
```


```{r fig.height=2.5, fig.width=10, message=FALSE, warning=FALSE}
Concentration_rxns_and_transps %>% get_two_Entrez_gene_lists %>% purrr::set_names(c("Reactions","Transporters")) %>% 
  compareCluster(fun='enrichPathway', pvalueCutoff=1e-3, qvalueCutoff=1e-3)-> enrich_output
enrich_output %>% dotplot(showCategory = 10, font.size = 8, label_format =90)+
   theme( 
    legend.text=element_text(size=6),
    legend.position = "bottom",
    #legend.box = "vertical",
    text = element_text(size=6)) -> C_enrichPathway
#ggarrange(C_enrichPathway, C_volcano, nrow = 1) -> upper_panel
```

```{r fig.height=3.5, fig.width=10, message=FALSE, warning=FALSE}
Flux_rxns_and_transps %>% get_two_Entrez_gene_lists %>% purrr::set_names(c("Reactions","Transporters")) %>% 
  compareCluster(fun='enrichPathway', pvalueCutoff=1e-3, qvalueCutoff=1e-3)-> enrich_output
enrich_output %>% dotplot(showCategory = 10, font.size = 8, label_format =90)+
   theme( 
    legend.text=element_text(size=6),
    legend.position = "bottom",
    #legend.box = "vertical",
    text = element_text(size=6)) -> F_enrichPathway
#ggarrange(F_enrichPathway, F_volcano, nrow = 1, widths = c(1,1.2)) -> middle_panel
```


```{r fig.height=2.5, fig.width=10, message=FALSE, warning=FALSE}
FluxConcentration_rxns_and_transps %>% get_two_Entrez_gene_lists %>% purrr::set_names(c("Reactions","Transporters")) %>% 
  compareCluster(fun='enrichPathway', pvalueCutoff=1e-3, qvalueCutoff=1e-3)-> enrich_output
enrich_output %>% dotplot(showCategory = 10, font.size = 8, label_format =90)+
   theme( 
    legend.text=element_text(size=6),
    legend.position = "bottom",
    #legend.box = "vertical",
    text = element_text(size=6)) -> FC_enrichPathway
#ggarrange(FC_enrichPathway, CF_volcano, nrow = 1, widths = c(1,1.2)) -> lower_panel
```




```{r fig.height=18, fig.width=18, message=FALSE, warning=FALSE}


setwd("/DeepenData/Repos/geometric_cobra")
ggsave("./results/figures/Figure_4_volcano_panel_subplot.png", volcanos_panel, height = 10, width = 10, bg="white", dpi = 400)


enrichment_panel <-  ggarrange(C_enrichPathway, F_enrichPathway, FC_enrichPathway, ncol = 1, common.legend = T, heights = c(.7,1.1,1), labels = c("a","c","e"))


ggarrange(enrichment_panel, volcanos_panel, nrow = 1, widths = c(1,1.6)) -> full_panel

full_panel
```


```{r}
setwd("/DeepenData/Repos/geometric_cobra")
ggsave("./results/figures/Figure_4.png", full_panel, height = 13, width = 15.2, bg="white", dpi = 500)

```



```{r}
get_DEG_table <- function(rxns_and_transps, gene_set){
              get_processed_results(annotated_results, rxns_and_transps %>% get_two_Entrez_gene_lists %>% .[[gene_set]]) -> DEG_table
              return(DEG_table)
}


get_DEG_table(Concentration_rxns_and_transps, "rxns")     %>% filter(padj < .05 & abs(log2FoldChange) > 0.1) -> DEGs_rxns_C
get_DEG_table(Concentration_rxns_and_transps, "trns")     %>% filter(padj < .05 & abs(log2FoldChange) > 0.1) -> DEGs_trns_C
get_DEG_table(Flux_rxns_and_transps, "rxns")              %>% filter(padj < .01 & abs(log2FoldChange) > 0.1) -> DEGs_rxns_F
get_DEG_table(Flux_rxns_and_transps, "trns")              %>% filter(padj < .01 & abs(log2FoldChange) > 0.1) -> DEGs_trns_F
get_DEG_table(FluxConcentration_rxns_and_transps, "rxns") %>% filter(padj < .01 & abs(log2FoldChange) > 0.1) -> DEGs_rxns_CF
get_DEG_table(FluxConcentration_rxns_and_transps, "trns") %>% filter(padj < .01 & abs(log2FoldChange) > 0.1) -> DEGs_trns_CF
```
```{r fig.height=4, fig.width=4, message=FALSE, warning=FALSE}
library(ggvenn)
l <- list(
DEGs_C = c(DEGs_rxns_C$hgnc_symbol, DEGs_trns_C$hgnc_symbol),
DEGs_F =  c(DEGs_rxns_F$hgnc_symbol, DEGs_trns_F$hgnc_symbol),
DEGs_CF = c(DEGs_rxns_CF$hgnc_symbol, DEGs_trns_CF$hgnc_symbol))

ggvenn(l,  stroke_size = 0.4,  set_name_size = 2, text_size = 3.5, show_elements = F) -> supplemental_venn_diagram



setwd("/DeepenData/Repos/geometric_cobra")
ggsave("./results/figures/supplemental_venn_diagram.png", supplemental_venn_diagram, height = 4, width = 4, bg="white", dpi = 400)
```
```{r}
DEGs_C = c(DEGs_rxns_C$hgnc_symbol, DEGs_trns_C$hgnc_symbol)
DEGs_F =  c(DEGs_rxns_F$hgnc_symbol, DEGs_trns_F$hgnc_symbol)
DEGs_CF = c(DEGs_rxns_CF$hgnc_symbol, DEGs_trns_CF$hgnc_symbol)

all_genes <- c(DEGs_C, DEGs_F, DEGs_CF) %>% unique()




get_gene_row <- function(a_gene){
                      gene_row <-  c("","","")
                      if(a_gene %in% DEGs_C){gene_row[1] <-  "\U1F5F8"}
                      if(a_gene %in% DEGs_F){gene_row[2] <-  "\U1F5F8"}
                      if(a_gene %in% DEGs_CF){gene_row[3] <-  "\U1F5F8"}
                      return(gene_row)
                      }

#a_gene    <- 'UYURT'
my_rows <- tibble()



for (a_gene in all_genes){
  a_row <- get_gene_row(a_gene)
 my_rows <- rbind(my_rows, a_row)
}

names(my_rows) <- c("Conc","Flux","Conc+Flux")

my_rows["hgnc_symbol"] <- all_genes



inner_join(my_rows, 
           annotated_results[c("hgnc_symbol", "entrezgene_id", "description")] %>% unique
           )%>% dplyr::group_by(Conc, Flux) %>% arrange(desc("Conc+Flux"), .by_group=T) ->annotated_gene_groups




first_part <- ceiling(nrow(annotated_gene_groups)/2)



annotated_gene_groups[1:(first_part+20),]                                -> annotated_gene_groups_1
annotated_gene_groups[(first_part+20+1):nrow(annotated_gene_groups),]  -> annotated_gene_groups_2


```


```{r fig.height=12.5, fig.width=10.5, message=FALSE, warning=FALSE}
base_size =8

main.title <- "Supplementary Table 1"
annotated_gene_groups_1 %>% ggtexttable(rows = NULL,theme = ttheme('mBlue', base_size = base_size,  padding = unit(c(1.4, 1.4), "mm"))) %>%
  tab_add_title(text = main.title, face = "bold", padding = unit(.5, "line"), size = 10, hjust = .09)  %>%
 tab_add_footnote(text = "(Continued on next page)", size = 8, face = "italic") -> supplementary_gene_table_1_first



setwd("/DeepenData/Repos/geometric_cobra")
ggsave("./results/figures/supplementary_gene_table_1_first.png", supplementary_gene_table_1_first, height = 10.5, width = 8, bg="white", dpi = 400)
```


```{r fig.height=12.5, fig.width=9, message=FALSE, warning=FALSE}
base_size =8

main.title <- "(Continued from previous page)"
annotated_gene_groups_2 %>% ggtexttable(rows = NULL, theme = ttheme('mBlue', base_size = base_size,  padding = unit(c(1.4, 1.4), "mm"))) %>%
  tab_add_title(text = main.title, face = "bold", padding = unit(.5, "line"), size = 8, hjust = .07) -> supplementary_gene_table_1_second


setwd("/DeepenData/Repos/geometric_cobra")
ggsave("./results/figures/supplementary_gene_table_1_second.png", supplementary_gene_table_1_second, height = 5, width = 7, bg="white", dpi = 200)

```





```{r}
get_Biological_Processes <- function(DEGs){
  temp <- getBM(attributes=c('hgnc_symbol',"entrezgene_id", 'entrezgene_description','namespace_1003','name_1006', 'definition_1006'),filters ='hgnc_symbol',values =DEGs$hgnc_symbol, mart = Hs.ensembl)
temp %>% dplyr::filter(namespace_1003 == "biological_process") -> df
df %>% dplyr::select(c(hgnc_symbol, entrezgene_description, entrezgene_id, name_1006)) %>% nest_by(hgnc_symbol, entrezgene_description, entrezgene_id) %>% mutate(data =paste0( purrr::flatten_chr(data) , collapse = ', ')) %>%dplyr::rename('Biological Processes' = data) -> df_annot
return(df_annot)
}
Biological_Processes <- map(list(DEGs_rxns_C, DEGs_trns_C, DEGs_rxns_F, DEGs_trns_F, DEGs_rxns_CF, DEGs_trns_CF),get_Biological_Processes)

```


```{r fig.height=2, fig.width=25, message=FALSE, warning=FALSE}
library(openxlsx)
setwd("/DeepenData/Repos/geometric_cobra")


xlsx_path <- "./results/genes/Supplementary_Table_1_Differential_expressed_genes.xlsx"

openxlsx::write.xlsx(Biological_Processes[[1]], file = xlsx_path,  sheetName = "s1_reactions_from_concentration", append = T)

add_new_sheet <- function(xlsx_path, sheet_name, data_to_sheet ){
wb <- loadWorkbook(xlsx_path)
addWorksheet(wb,sheet_name)
writeData(wb,sheet_name,data_to_sheet)
saveWorkbook(wb,xlsx_path,overwrite = TRUE)}

add_new_sheet(xlsx_path,"s2_transport_from_concentration",Biological_Processes[[2]])
add_new_sheet(xlsx_path,"s3_reactions_from_flux",Biological_Processes[[3]])
add_new_sheet(xlsx_path,"s4_transport_from_flux",Biological_Processes[[4]])
add_new_sheet(xlsx_path,"s5_reactions_from_conc_and_flux",Biological_Processes[[5]])
add_new_sheet(xlsx_path,"s6_transport_from_conc_and_flux",Biological_Processes[[6]])

```





