---
title: "R Notebook"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(magrittr)
library(ggbeeswarm)
library(ggpubr)
setwd("/DeepenData/Repos/geometric_cobra")
metabolites_outliers_imputed           <- arrow::read_parquet("./processed_data/augmented_balanced_metabolite_data.parquet.gzip") %>% as_tibble()%>%
  rename( Group = label) %>% mutate(Group = if_else(Group == 1,'PKU','Control')) %>%
  mutate(Group = as.factor(Group))  %>% 
  rename("C4OH+C3DC" = C4OH.C3DC, "C5.OH+C4DC" = C5.OH.C4DC, "Leu+Ile" = Leu.Ile)

table(
metabolites_outliers_imputed$Group
)
```
```{r fig.height=5, fig.width=2}
color_1 <- "dodgerblue2" 

color_2 <- "red4"

get_concentration_subplot <- function(input_df, vars_subset, logscale =F, legend.position = 'none', y_label = F, angle = 45, swarm_width = .15, dodge.width = 1, point_size = .9, size_ticks_size = 9, axis_title_size = 12, gray = F){
  Control_df <-  input_df %>% dplyr::filter(Group == "Control")  %>%  dplyr::slice_sample(n=200)


PKU_df <-  input_df %>% dplyr::filter(Group == "PKU") 

subsample <- rbind(PKU_df, Control_df)
subsample %>% dplyr::select(c(vars_subset, 'Group')) %>% pivot_longer(-Group) -> df

df %>%                                 ggplot(aes(x= reorder(name, -value), y=value, color=Group)) -> P0

if(gray){P0 <- P0  + theme_gray() }else{ P0 <- P0  + theme_minimal()}
                                 
                                  
                                  
                                  
                                P0 + geom_boxplot(width = .15, outlier.shape = NA)    +
  geom_point(position=position_quasirandom(dodge.width = dodge.width, width = swarm_width), alpha = .8, size =point_size) +
  scale_colour_manual(values = c(color_1 ,color_2))  + 
   theme(axis.title.x = element_blank(),axis.text.x = element_text(angle = angle, vjust = 0, hjust=.5),axis.text = element_text(size = size_ticks_size),axis.title = element_text(size = axis_title_size),
                                  legend.position=legend.position,
                                 legend.text = element_text(size=7))-> p

if(logscale){p <-p  + coord_trans( y="log2")}
if(y_label){p <-p   + ylab(expression(mu*"M"))}else{p <-p   +theme(axis.title.y = element_blank())}

return(p )
  
}

metabolites_outliers_imputed     %>% 
                                 summarise(across(where(is.double),  ~ max(.x, na.rm = TRUE))) %>% 
                                 t %>% as.data.frame() %>% arrange(desc(V1)) %>% rownames() -> sorted_vars

setdiff(sorted_vars, c("Phe")) -> v
vars_intervals <- list()
j = 0
for (i in seq(from = 1, to = 44, by = 11)){
                                          j = j +1
                                          vars_intervals[[j]] <-v[i:(i+10)]
                                          if( (i+7) > 44 ){ vars_intervals[[j]] <-v[i:(44)]}
                                         }


#vars_intervals[[5]] <- c(vars_intervals[[5]], vars_intervals[[6]])
# vars_intervals[[6]] <- NULL

 
get_concentration_subplot(metabolites_outliers_imputed, 'Phe', T, 'top',  y_label = T,  angle=0, gray = T) -> p
p + geom_hline(yintercept=c(35,120, 360), linetype="dashed", 
                color = c("black","black","red"), size=.51)+ scale_y_continuous(breaks=c(35,120,360, 1000, 2300)) +
  theme(legend.title=element_blank()) -> Phe_


Phe_  + stat_compare_means(label = "p.signif", method = 'wilcox.test') -> Phe_

#Phe_subplot <- ggarrange(Phe_ , labels = 'a' )
```


```{r fig.height=5, fig.width=2}
get_concentration_subplot(metabolites_outliers_imputed, 'Tyr', T, 'top',  y_label = F,  angle=0, gray = T) -> p
p + # geom_hline(yintercept=c(20,50, 150), linetype="dashed",                 color = c("azure4","azure4","azure4"), size=.51)+ 
  scale_y_continuous(breaks=c(20,50,150)) +
  theme(legend.title=element_blank()) -> Tyr_

Tyr_  + stat_compare_means(label = "p.signif", method = 'wilcox.test') -> Tyr_
```


```{r fig.height=5, fig.width=3.5}

ggarrange(Phe_, Tyr_, common.legend = T, widths = c(1.06,1),labels = c("a","b") ) -> Phe_subplot

```











