---
title: "R Notebook"
output: html_notebook
---



```{r message=FALSE, warning=FALSE}
library(arrow)
library(tidyverse)
library(ComplexHeatmap) 
library(scales)
library(ggpubr)
library(ggplot2)
library(DOSE)
library(magrittr)
library(biomaRt)
library(tidyverse)
library(clusterProfiler)
library(ReactomePA)
library(org.Hs.eg.db)
library(fastcluster)

get_processed_data <- function(df, percentile,labels){
                                  edge_weights_x_patients <- df%>%  dplyr::select_if(is.numeric)
                                  edge_weights_x_patients %<>% t %>% scale %>% t   %>%as.data.frame()
                                  edge_weights_x_patients %>% abs()   %>%  rowSums() -> all_edge_scores
                                  edges_genes   <- df%>%  dplyr::select_if(is.character)
                                  edges_genes['all_edge_scores'] <- all_edge_scores
                                  #edges_genes %>% dplyr::arrange(desc(all_edge_scores))
                                  cutoff <- quantile(all_edge_scores, probs =percentile )
                                  mask <- all_edge_scores > cutoff
                                  edges_genes[mask,] -> edges_genes#%>% arrange(desc(all_edge_scores))
                                  edge_weights_x_patients[mask,] -> edge_weights_x_patients
                                  rownames(edge_weights_x_patients) <- NULL
                                  n_edges <- nrow(edges_genes)
                                  n_patients <- length(labels)
                                  edges_mask    <- sample(c(T,F), n_edges, replace = T, prob = c(1, 0))
                                  patients_mask <- sample(c(T,F), n_patients, replace = T, prob = c(1, 0))
                                  edge_weights_x_patients_SAMPLE <- edge_weights_x_patients[edges_mask,patients_mask]
                                  labels_SAMPLE <- labels[patients_mask]
                                  edges_genes_SAMPLE <- edges_genes[edges_mask,]
                                  processed_data <- edge_weights_x_patients_SAMPLE %>% as.matrix() %>% rescale
                                  return(list(processed_data,all_edge_scores,cutoff, labels_SAMPLE, edges_genes_SAMPLE,mask))}
```


```{r message=FALSE, warning=FALSE}
setwd("/DeepenData/Repos/geometric_cobra")


df_flux     <-    read_csv("./results/explanations/to_functional_R_heatmap_explanatory_subgraph_MASKED_GIN_Fluxes.csv") %>% dplyr::select(-c("...1"))

labels_flux <- read_csv("./results/dataloaders/labels_masked_only_Fluxes.csv")  %>%  dplyr::select(-c("...1")) %>% .[[1]] #test_labels_masked_NONflux.csv  #test_labels_masked_FLUX.csv

data_plus_labels <- get_processed_data(df_flux, .90, labels_flux)

data_plus_labels[[1]] -> processed_data
data_plus_labels[[5]] -> edges_genes_SAMPLE

#cbind(edges_genes_SAMPLE,processed_data)
edges_genes_SAMPLE['all_edge_scores'] <- scales::rescale(edges_genes_SAMPLE$all_edge_scores, c(0,1))

write_csv(edges_genes_SAMPLE,  "./results/explanations/to_GraphTools_visualization_explanatory_subgraph_MASKED_GIN_FLUX.csv")
    #"./results/dataframes/new_to_R_heatmap_explanatory_subgraph_MASKED_GIN_Concentration.csv"

    #"./results/dataframes/new_to_R_heatmap_explanatory_subgraph_MASKED_GIN_Concen_plus_Fluxes.csv"
```


```{r message=FALSE, warning=FALSE}
setwd("/DeepenData/Repos/geometric_cobra")


df_flux     <-    read_csv("./results/explanations/to_functional_R_heatmap_explanatory_subgraph_MASKED_GIN_Concentration.csv") %>% dplyr::select(-c("...1"))

labels_flux <- read_csv("./results/dataloaders/labels_masked_only_Concen.csv")  %>%  dplyr::select(-c("...1")) %>% .[[1]] #test_labels_masked_NONflux.csv  #test_labels_masked_FLUX.csv

data_plus_labels <- get_processed_data(df_flux, .991, labels_flux)

data_plus_labels[[1]] -> processed_data
data_plus_labels[[5]] -> edges_genes_SAMPLE

#cbind(edges_genes_SAMPLE,processed_data)
edges_genes_SAMPLE['all_edge_scores'] <- scales::rescale(edges_genes_SAMPLE$all_edge_scores, c(0,1))

write_csv(edges_genes_SAMPLE,  "./results/explanations/to_GraphTools_visualization_explanatory_subgraph_MASKED_GIN_Concentration.csv")

```


```{r message=FALSE, warning=FALSE}

setwd("/DeepenData/Repos/geometric_cobra")


df_flux     <-    read_csv("./results/explanations/to_functional_R_heatmap_explanatory_subgraph_MASKED_GIN_Concen_plus_Fluxes.csv") %>% dplyr::select(-c("...1"))

labels_flux <- read_csv("./results/dataloaders/labels_masked_Concen_plus_Fluxes.csv")  %>%  dplyr::select(-c("...1")) %>% .[[1]] #test_labels_masked_NONflux.csv  #test_labels_masked_FLUX.csv

data_plus_labels <- get_processed_data(df_flux, .90, labels_flux)

data_plus_labels[[1]] -> processed_data
data_plus_labels[[5]] -> edges_genes_SAMPLE

#cbind(edges_genes_SAMPLE,processed_data)
edges_genes_SAMPLE['all_edge_scores'] <- scales::rescale(edges_genes_SAMPLE$all_edge_scores, c(0,1))

write_csv(edges_genes_SAMPLE,  "./results/explanations/to_GraphTools_visualization_explanatory_subgraph_MASKED_GIN_Concen_plus_Fluxes.csv")

```
















