---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
library(arrow)
library(tidyverse)
library(ComplexHeatmap) 
library(scales)
library(ggpubr)
library(ggplot2)
library(DOSE)
library(magrittr)
library(biomaRt)
library(tidyverse)
library(clusterProfiler)
library(ReactomePA)
library(org.Hs.eg.db)
library(fastcluster)
```


```{r message=FALSE, warning=FALSE}
setwd("/DeepenData/Repos/geometric_cobra")
Cluster_genes_concentration <- read_csv( "./results/dataframes/Cluster_genes_concentration.csv")
Cluster_genes_flux <- read_csv( "./results/dataframes/Cluster_genes_flux.csv")
Cluster_genes_concentration_plus_flux <- read_csv( "./results/dataframes/Cluster_genes_concentration_plus_flux.csv")
```
```{r message=FALSE, warning=FALSE}
get_gene_cluster<- function(df, a_cluster){
                  genes <-  df %>%  dplyr::filter(Cluster == a_cluster)   %>%  .[['genes']]  %>% str_extract_all('\\d+(?=\\.)') %>% unlist() %>% unique()
                  return(genes
                       
                        )}


get_clusters_list <- function(df){
                                clusters_list <- list(
                              "1" = get_gene_cluster(df, 1),
                              "2" = get_gene_cluster(df, 2))
                              return(clusters_list)
                              }



get_clusters_list(Cluster_genes_concentration)           -> concentration
get_clusters_list(Cluster_genes_flux)                    -> flux
get_clusters_list(Cluster_genes_concentration_plus_flux) -> concentration_plus_flux
```


```{r message=FALSE, warning=FALSE}
ensembl    <- useMart("ensembl")
Hs.ensembl <- useMart("ensembl",dataset="hsapiens_gene_ensembl")
genes_symbols <- list()
get_functional_annots <- function(entrez_IDs, transporters){
                                   temp <- getBM(attributes=c('hgnc_symbol',"entrezgene_id", 'entrezgene_description'),filters ='entrezgene_id',values =entrez_IDs, mart = Hs.ensembl)
                                   if(transporters){
                                     temp %<>% filter(str_detect(entrezgene_description,regex( '(solute.+?carrier)|transporter|aquapor|transport', ignore_case = T))) 
                                   }
                                   else {  temp %<>% filter(!str_detect(entrezgene_description,regex( '(solute.+?carrier)|transporter|aquapor|transport', ignore_case = T))) }
                                   
                                   
                                   
                                   return(arrange(temp, hgnc_symbol) %>% purrr::set_names(c("Symbol", "Entrez ID", "Description")))}


get_transporters_and_reactions <- function(clusters_list){
  transporters <- purrr::map2(clusters_list, c(T,T), get_functional_annots)
reactions    <- purrr::map2(clusters_list, c(F,F), get_functional_annots)
transporters_and_reactions <- list('reactions'=reactions,'transporters'=transporters)

purrr::map2(transporters_and_reactions$reactions, c("Entrez ID","Entrez ID"), pull) -> reaction_genes
purrr::map2(transporters_and_reactions$transporters, c("Entrez ID","Entrez ID"), pull) -> transporter_genes

return(list("reactions"= reaction_genes,  'transporters'=transporter_genes))
  
}

```


```{r message=FALSE, warning=FALSE}
get_transporters_and_reactions(concentration) -> transporters_and_reactions_concentration
get_transporters_and_reactions(flux) -> transporters_and_reactions_flux
get_transporters_and_reactions(concentration_plus_flux) -> transporters_and_reactions_concentration_plus_flux
```


```{r message=FALSE, warning=FALSE}
setwd("/DeepenData/Repos/geometric_cobra")
transporters_and_reactions_concentration %>% unlist %>% as.vector() %>% data.frame("C"= .) %>% write_csv("./results/dataframes/entrez_IDs_C.csv")

transporters_and_reactions_flux %>% unlist %>% as.vector()  %>% data.frame("F"= .) %>% write_csv("./results/dataframes/entrez_IDs_F.csv")

transporters_and_reactions_concentration_plus_flux%>% unlist %>% as.vector() %>% data.frame("CF"= .)  %>% write_csv("./results/dataframes/entrez_IDs_CF.csv")

```

-----

# Transporters_and_reactions_concentration


```{r fig.height=2, fig.width=4, message=FALSE, warning=FALSE}
transporters_and_reactions_concentration$reactions %>% 
  compareCluster(fun='enrichPathway', pvalueCutoff=1e-3, qvalueCutoff=1e-3)-> enrich_output
enrich_output %>% dotplot(showCategory = 10, font.size = 5, label_format =90)+
   theme( 
    legend.text=element_text(size=6),
    legend.position = "bottom",
    #legend.box = "vertical",
    text = element_text(size=6)) -> concentration_reactions_enrichPathway
concentration_reactions_enrichPathway
```


```{r fig.height=2, fig.width=4, message=FALSE, warning=FALSE}
transporters_and_reactions_concentration$transporters %>% 
  compareCluster(fun='enrichPathway', pvalueCutoff=1e-6, qvalueCutoff=1e-5)-> enrich_output
enrich_output %>% dotplot(showCategory = 10, font.size = 5, label_format =90)+
   theme( 
    legend.text=element_text(size=6),
    legend.position = "bottom",
    #legend.box = "vertical",
    text = element_text(size=6)) -> concentration_transporters_enrichPathway

concentration_transporters_enrichPathway
```


```{r fig.height=2, fig.width=4, message=FALSE, warning=FALSE}

transporters_and_reactions_concentration$reactions %>% compareCluster(fun='enrichDGN', pvalueCutoff=5e-2,  qvalueCutoff=5e-2)-> enrich_output
enrich_output %>% dotplot(showCategory = 10, font.size = 6, label_format =80)+
   theme( 
    legend.text=element_text(size=6),
    legend.position = "bottom",
    #legend.box = "vertical",
    text = element_text(size=6))  -> concentration_reactions_enrichDGN
```




```{r fig.height=2, fig.width=4, message=FALSE, warning=FALSE}

transporters_and_reactions_concentration$transporters %>% compareCluster(fun='enrichDGN', pvalueCutoff=5e-2,  qvalueCutoff=5e-2)-> enrich_output
enrich_output %>% dotplot(showCategory = 3, font.size = 6, label_format =80)+
   theme( 
    legend.text=element_text(size=6),
    legend.position = "bottom",
    #legend.box = "vertical",
    text = element_text(size=6))  -> concentration_transporters_enrichDGN
```



```{r fig.height=4, fig.width=4}
#concentration_panel <- ggarrange(concentration_reactions_enrichPathway, concentration_transporters_enrichPathway, concentration_reactions_enrichDGN, concentration_transporters_enrichDGN, common.legend = T, labels = c("a", "b", "c", "d"), nrow = 1)


#annotate_figure (concentration_reactions_enrichPathway, left = text_grob("Reactions", color = "black", rot = 90,  size = 9),) ->concentration_reactions_enrichPathway
#annotate_figure (concentration_transporters_enrichPathway, left = text_grob("Transporters", color = "black", rot = 90,  size = 9),)->concentration_transporters_enrichPathway



concentration_panel <- ggarrange(concentration_reactions_enrichPathway, concentration_transporters_enrichPathway,common.legend = T, labels = c("a", "b"), nrow = 2)



annotate_figure(concentration_panel,

               top = text_grob("Metabolite abundance", color = "black", rot = 0,  size = 8),) -> concentration_panel

concentration_panel
```

##########################################
################---transporters_and_reactions_flux---#########################
##########################################


```{r fig.height=2, fig.width=4, message=FALSE, warning=FALSE}
transporters_and_reactions_flux$reactions %>% 
  compareCluster(fun='enrichPathway', pvalueCutoff=1e-11, qvalueCutoff=1e-11)-> enrich_output
enrich_output %>% dotplot(showCategory = 10, font.size = 5, label_format =90)+
   theme( 
    legend.text=element_text(size=6),
    legend.position = "bottom",
    #legend.box = "vertical",
    text = element_text(size=6)) -> flux_reactions_enrichPathway
flux_reactions_enrichPathway
```


```{r fig.height=2, fig.width=4, message=FALSE, warning=FALSE}
transporters_and_reactions_flux$transporters %>% 
  compareCluster(fun='enrichPathway', pvalueCutoff=1e-15, qvalueCutoff=1e-15)-> enrich_output
enrich_output %>% dotplot(showCategory = 10, font.size = 5, label_format =90)+
   theme( 
    legend.text=element_text(size=6),
    legend.position = "bottom",
    #legend.box = "vertical",
    text = element_text(size=6))-> flux_transporters_enrichPathway
flux_transporters_enrichPathway
```


```{r fig.height=2, fig.width=4, message=FALSE, warning=FALSE}

transporters_and_reactions_flux$reactions %>% compareCluster(fun='enrichDGN', pvalueCutoff=5e-2,  qvalueCutoff=5e-2)-> enrich_output
enrich_output %>% dotplot(showCategory = 3, font.size = 6, label_format =80)+
   theme( 
    legend.text=element_text(size=6),
    legend.position = "bottom",
    #legend.box = "vertical",
    text = element_text(size=6))-> flux_reactions_enrichDGN
```




```{r fig.height=2, fig.width=4, message=FALSE, warning=FALSE}

transporters_and_reactions_flux$transporters %>% compareCluster(fun='enrichDGN', pvalueCutoff=5e-2,  qvalueCutoff=5e-2)-> enrich_output
enrich_output %>% dotplot(showCategory = 3, font.size = 6, label_format =80)+
   theme( 
    legend.text=element_text(size=6),
    legend.position = "bottom",
    #legend.box = "vertical",
    text = element_text(size=6)) -> flux_transporters_enrichDGN
```

```{r fig.height=4, fig.width=8}
#flux_panel <- ggarrange(flux_reactions_enrichPathway, flux_transporters_enrichPathway, flux_reactions_enrichDGN, flux_transporters_enrichDGN, common.legend = T, labels = c("e", "f", "g", "h"), nrow = 1)


flux_panel <- ggarrange(flux_reactions_enrichPathway, flux_transporters_enrichPathway, common.legend = T, labels = c("c", "d"), nrow = 2)

annotate_figure(flux_panel,

               top = text_grob("Flux", color = "black", rot = 0,  size = 8),) -> flux_panel

flux_panel




```
##########################################
################---transporters_and_reactions_concentration_plus_flux---#########################
##########################################
```{r fig.height=2, fig.width=4, message=FALSE, warning=FALSE}
transporters_and_reactions_concentration_plus_flux$reactions %>% 
  compareCluster(fun='enrichPathway', pvalueCutoff=5e-5, qvalueCutoff=5e-5)-> enrich_output
enrich_output %>% dotplot(showCategory = 10, font.size = 5, label_format =90)+
   theme( 
    legend.text=element_text(size=6),
    legend.position = "bottom",
    #legend.box = "vertical",
    text = element_text(size=6)) ->concentration_plus_flux_reactions_enrichPathway
concentration_plus_flux_reactions_enrichPathway
```


```{r fig.height=2, fig.width=4, message=FALSE, warning=FALSE}
transporters_and_reactions_concentration_plus_flux$transporters %>% 
  compareCluster(fun='enrichPathway', pvalueCutoff=1e-11, qvalueCutoff=1e-11)-> enrich_output
enrich_output %>% dotplot(showCategory = 10, font.size = 5, label_format =90)+
   theme( 
    legend.text=element_text(size=6),
    legend.position = "bottom",
    #legend.box = "vertical",
    text = element_text(size=6)) -> concentration_plus_flux_transporters_enrichPathway
concentration_plus_flux_transporters_enrichPathway
```


```{r fig.height=2, fig.width=4, message=FALSE, warning=FALSE}

transporters_and_reactions_concentration_plus_flux$reactions %>% compareCluster(fun='enrichDGN', pvalueCutoff=5e-2,  qvalueCutoff=5e-2)-> enrich_output
enrich_output %>% dotplot(showCategory = 3, font.size = 6, label_format =80)+
   theme( 
    legend.text=element_text(size=6),
    legend.position = "bottom",
    #legend.box = "vertical",
    text = element_text(size=6)) -> concentration_plus_flux_reactions_enrichDGN
```


```{r fig.height=2, fig.width=4, message=FALSE, warning=FALSE}

transporters_and_reactions_concentration_plus_flux$transporters %>% compareCluster(fun='enrichDGN', pvalueCutoff=5e-2,  qvalueCutoff=5e-2)-> enrich_output
enrich_output %>% dotplot(showCategory = 3, font.size = 6, label_format =80)+
   theme( 
    legend.text=element_text(size=6),
    legend.position = "bottom",
    #legend.box = "vertical",
    text = element_text(size=6)) -> concentration_plus_flux_transporters_enrichDGN
```

```{r fig.height=3, fig.width=3}
#concentration_flux_panel <- ggarrange(concentration_plus_flux_reactions_enrichPathway, concentration_plus_flux_transporters_enrichPathway, concentration_plus_flux_reactions_enrichDGN, concentration_plus_flux_transporters_enrichDGN, common.legend = T, labels = c("i", "j", "k", "l"), nrow = 1)

concentration_flux_panel <- ggarrange(concentration_plus_flux_reactions_enrichPathway, concentration_plus_flux_transporters_enrichPathway, common.legend = T, labels = c("e", "f"), nrow = 2)



annotate_figure(concentration_flux_panel,

               top = text_grob("Abundance and flux", color = "black", rot = 0,  size = 8),) -> concentration_flux_panel

concentration_flux_panel

```


```{r fig.height=4, fig.width=13}
annotate_figure(concentration_panel,

             left = text_grob("              Reactions                            Transporters        ", color = "black", rot = 90,  size = 8),) -> concentration_panel_final



ggarrange(concentration_panel_final, flux_panel, concentration_flux_panel, ncol = 3)  -> full_panel
full_panel
```


```{r fig.height=5, fig.width=12}

setwd("/DeepenData/Repos/geometric_cobra")
ggsave("./results/figures/figure_4.png", full_panel, height = 4, width = 13, bg="white")

```






































